### ISSUE TITLE
RPT log error when spawning AI units

### ISSUE THREAD

**Issue by Nerexis** [nk3nny/LambsDanger#153] opened 2020-08-14 09:47 UTC
I'm getting below error in RPT logs, when spawning AI units:

```
11:31:57 Error in expression <dex, _sound];
} forEach _cachedSounds;

lambs_danger_CalloutCacheNamespace setVa>
11:31:57   Error position: <lambs_danger_CalloutCacheNamespace setVa>
11:31:57   Error Undefined variable in expression: lambs_danger_calloutcachenamespace
11:31:57 File z\lambs\addons\danger\functions\fnc_doCallout.sqf..., line 88
11:31:57 Error in expression <ior, _callout];
private _cachedSounds = lambs_danger_CalloutCacheNamespace getVa>
11:31:57   Error position: <lambs_danger_CalloutCacheNamespace getVa>
11:31:57   Error Undefined variable in expression: lambs_danger_calloutcachenamespace
11:31:57 File z\lambs\addons\danger\functions\fnc_doCallout.sqf..., line 38
```

**Comment by jokoho48** [comment] 2020-08-14 09:48
Please fill out the issue template.

**Comment by DEH4NK** [comment] 2020-08-28 09:43
My complete server RPT with error
[https://sqfbin.com/aqomukuxowapulohatot](url)

**Comment by jokoho48** [comment] 2020-08-29 09:48
duplicate of #155

**Closed by jokoho48** 2020-08-29 09:48 UTC
Labels: need more informations
