### ISSUE TITLE
Civilian danger response issues (dangerCivilian.fsm)

### ISSUE THREAD

**Issue by DarkWanderer** [nk3nny/LambsDanger#163] opened 2020-09-27 16:56 UTC
**Mods (complete and add to the following information):**

- **Arma 3:** `1.98 stable`
- **CBA:** `3.15.1`
- **LAMBS_DANGER:** `2.4.4`

**Description:**

Civilian _agents_ display rather strange reaction to gunfire. 
Specifically:
1. When first shooting near a civilian agent, he will run away in panic (as expected). However, subsequent shots, even very close, do not cause further panic/movement. 
2. Sometimes panic animation does not trigger. Combined with previous point - this results in civilians running into open field and standing there, apparently oblivious to fire
3. Nearby explosions will cause to play strange set of animations (looking as if the civilian holds a gun in hands)

**Steps to reproduce:**

- Create empty mission in editor, place player
- Start mission
- Execute code: `createAgent ["C_man_p_beggar_F_euro", getPos player, [], 0, "NONE"];`
- Shoot near spawned civilian
- Wait 2-3 minutes
- Shoot near him again
- Throw a grenade nearby (not close enough to damage)
- Shoot civilian directly

**Expected behavior:**

1. Civilians in panic state should still react to nearby gunfire/explosions
2. Civilians should not "hang" just standing in open field
3. Nearby explosions should not cause "I have a weapon" animation

**Where did the issue occur?**

- Editor (Singleplayer)

**Additional context:**

Demonstration video (without the waiting, but displays the unresponsive behavior+animation issue well): https://youtu.be/pNUsRHThc7s

P.S. Of course I appreciate this being new functionality, but if anyone plans another iteration on the civilian danger fsm, I think a little feedback would be useful

**Comment by nk3nny** [comment] 2020-10-04 09:51
Thank you for the excellent bugreport.  I haven't explored the interaction with Agents in any big way, but I have also noticed some inconsistencies in civilian behaviour.

**Comment by nk3nny** [comment] 2020-10-12 20:42
This has been improved quite a bit for version 2.5.  The problem is complicated.  Civilians (and their agents) seem to have a less frequent update of FSM than combatant units do.  Which means it cannot be relied upon as easily to handle (or even trigger!) when reacting to violent imperatives. 

Future versions may see the civilian handling of the AI moved to its own .pbo with a fully new FSM made to support it. 

This issue will remain open for 24h before closing.

**Comment by DarkWanderer** [comment] 2020-10-13 08:18
Thanks, looking forward to it. 

While we're at the topic - is there a way to detect when LAMBS' danger FSM is currently active for an 'agent' (or can such feature be planned)? I'm looking to manage higher-level civilian functions in a module and don't want to override danger response with "walking around" behavior.

**Comment by nk3nny** [comment] 2020-10-13 12:42
@DarkWanderer 
Excellent point. I will fix that before the release. You can also read the current Queue brain state by checking  "lambs_danger_FSMDangerCauseData", which I will also add to the civilian FSM.

**Closed** 2021-02-08 11:57 UTC
